### ISSUE TITLE
Need a way to get back to all projects when using category filters

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#100]
Once a user clicks one of the top category filters, there is no way to go back to show all projects other than clicking the Projects tab again.  Once you click a filter, lets make it so if you click it again, it deselects the filter and once again shows all projects.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/de2aa609-c8b1-406b-805c-36af183c30bf)

**Comment by Chirag018** [comment]
working on this!
