### ISSUE TITLE
View shift when changing categories (and scroll bar appears)

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#101]
There is a jarring shift when you change between a category that has many items and one that has few due to the scroll bar appearing/disappearing on the right of the view.  This shifts the projects view and some items in the header slightly.

![CategoryShift](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/1c104791-8aa1-4260-a138-c43b300c211c)

**Comment by ZakGriffith** [comment]
For me, it happens when using Chrome or Firefox at a 100% zoom.  If I change the zoom to more or less it does not happen.  Might depend some on the resolution of the monitor as well.  Is the scroll bar appearing for you when you?  I don't see it on the right side of your screen.

**Comment by Chirag018** [comment]
Yeah, when the elements are more than the given size, a scroll automatically pops up. 

As in the above video in tooling, there are 7 elements so scroll gets going, while in other components there are fewer, so it doesn't pop's up

**Comment by Chirag018** [comment]
One way to test them can be to add more elements to other components to test them

**Comment by ZakGriffith** [comment]
Getting the same shift on the My Ballot page as well.  If no-one else is getting this, then we can just move on.  I am using a resolution of 2560x1440 with everything is scaled to 125% size.

![CategoryShift2](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/1ec4bbba-b349-46ee-b16f-6b1a323f0ec1)

**Comment by electrone901** [comment]
https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/10853211/3259c6ab-c08a-429c-a12c-08aef61d8d87

After taking the time to think and experiment with it, I didn't experience any sudden shifts during testing. I've tested it in three different browsers and even attached a quick video showing the testing on Brave, Chrome, and Firefox.

@ZakGriffith have you made any adjustments to the width of the scrollbar in your browser?

**Comment by ZakGriffith** [comment]
Yes, still happening when I click between a category with very little entries, to one with many.  But with the count of entries in the OP Retro PFG3 this is probably a non-issue.  Closing this one.
