### ISSUE TITLE
Remove View Ballot page scrollbar

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#102]
Let's remove the scroll bar from the View Ballot page and just have the projects added in a long vertical list.  They can scroll their browser down to get to them all.

Current view:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/e25282e5-f1b7-4c4a-949b-dde3c903d886)

**Comment by escottalexander** [comment]
I will do this one.
