### ISSUE TITLE
Remove some padding/margins from View Ballot page, make list page look the same.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#104]
To fit more projects in, let's lessen the padding/margins (Whatever is used here) on each project in the View Ballot page so more can be seen on one page.  Here is how it currently looks: 
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/db3494dd-0e82-4831-91d6-150175f35428)

But this would look a little sleeker and easier on the eyes:

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/f22759f7-e923-4ad7-833e-0d9180fb8916)

Then the view when you've clicked into a list, that page needs to have the same sizing/spacing as the above changes.  This should also be implemented into the "Edit Distribution" page when you are updating the distribution of a pre-existing List.  Same with the modal after clicking Add To Ballot from when you've clicked into a list.

Current List:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/015bf0f1-6d2b-4847-b902-bb24b790b467)

Current "Edit Distribution" when editing the distribution of a list before adding it to your own ballot:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/1ed8ed64-be52-4a86-82ff-85aa44864b79)

A good place to go to get an idea of the correct sizing/spacing is this view from the OP Figma:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/92991200-a05b-46d2-bfaf-d98bfec2191a)

Summary of changes:

- [x] View Ballot page spacing/size updates
- [x] Clicked into a list view spacing/size updates
- [x] List view - Edit Distribution spacing/size updates
- [x] List view - Add To Ballot spacing/size updates

**Comment by escottalexander** [comment]
I will knock this out.
