### ISSUE TITLE
In the wide view, projects are not links or clickable

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#105]
In this view of the projects 
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/e678d20c-8d4e-4b66-a69a-fcdc56c0583b)
each project is not clickable in any way.  These should be links the each project's page like it is in the grid view.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/a53bc792-3245-4f5f-9f65-eba28a18c9c3)

**Comment by escottalexander** [comment]
Woah! I got this one.
