### ISSUE TITLE
Overall background should be white

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#106]
The background to all pages should be white like in the OP Figma seen here:

<img width="1516" alt="💻 Projects › Connected - Grid View@2x" src="https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/858c0169-8312-4315-b763-6eb11a5af007">

There may be some extra items with this (Like adding borders to projects on the project grid view page) if necessary.

Pages that I have noticed that need updated are 👍 

- [ ] Projects tab
- [ ] Lists tab
- [ ] View when you click into a project
- [ ] View when you click into a list
- [ ] View Ballot/My Ballot page

**Comment by KcPele** [comment]
I will work on this

**Comment by KcPele** [comment]
#113 
![Screenshot from 2023-10-06 17-38-45](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/64108987/2cc782d1-6871-4aea-a81e-e1a7396d7ccd)

**Comment by ZakGriffith** [comment]
Closed in #113
