### ISSUE TITLE
My Ballot page needs a 'Submit Ballot' button to submit

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#108]
We need the ability for the user to submit their ballot from the  My Ballot page.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/81e29aa5-2ab1-4ae8-ae53-a91e6fb49dda)

**Comment by ZakGriffith** [comment]
We also the need the "Share as List" button here as well to create a new list.

**Comment by KcPele** [comment]
Working on this

**Comment by KcPele** [comment]
#113

**Comment by ZakGriffith** [comment]
Closed in #113
