### ISSUE TITLE
Easier editing of allocation in My Ballot page

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#109]
Currently editing the allocation on the My Ballot page requires clicking the three dot icon, then hitting edit, then changing the value and saving.  Lets make that easier and use an input and delete button just like how we do it in the List edit distribution page.  

Current My Ballot page:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/f7592516-13f4-46e0-b571-5bdae75077bb)

Easier solution(But no need to include the greyed out, previous, distribution like in this List screenshot):  
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/27978d08-1751-42bd-bdab-d219bad2d98c)

The input should be auto populated with the current allocation and also check for any allocations higher than the max. If they do type in a bigger number than allowed we should limit the number in the input and maybe even give them a warning message similar to the one in this modal:

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/8dd8d6d8-9327-4930-959d-a2dd983eeaef)

**Comment by escottalexander** [comment]
I will tackle this one.
