### ISSUE TITLE
Dark mode issues with Edit Distribution and Add List To Ballot modals

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#112]
We need to fix the dark mode version of these two modals.

Edit Distribution:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/eae198c4-d8d8-481d-9f0c-94e9bd3a7e8d)

Add List To Ballot:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/8250f361-9544-4afb-b95a-2be5339f2d46)

**Comment by KcPele** [comment]
working on this

**Comment by KcPele** [comment]
this issue should be closed right

**Comment by electrone901** [comment]
When saving a project to the ballot or to My ballot the letters are hard to see. 
 
![Screenshot 2023-10-24 at 1 10 34 PM](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/10853211/fe334714-b99f-4c05-92c9-509d41e27c27)

**Comment by ZakGriffith** [comment]
Good spot. I am going to close this one and create a new issue for that.
