### ISSUE TITLE
Shuffle is shuffling categories as well

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#116]
The categories should not be shuffling when using the Shuffle button in the project view.  Happens in both grid and list views of projects.

![ShuffleCategories](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/df6da3a1-33c7-43de-935b-deba3b94b2c4)

**Comment by blahkheart** [comment]
I don't face this problem on mine, possibly a recent fix may have introduced this bug. Maybe when my latest PR is reviewed and merged you can test again and see if it persists

**Comment by ZakGriffith** [comment]
Agreed, didn't see this behavior in your current PR.

**Comment by Chirag018** [comment]
> The categories should not be shuffling when using the Shuffle button in the project view. Happens in both grid and list views of projects.
> 
> ![ShuffleCategories](https://user-images.githubusercontent.com/12072395/273653677-df6da3a1-33c7-43de-935b-deba3b94b2c4.gif) [ ![ShuffleCategories](https://user-images.githubusercontent.com/12072395/273653677-df6da3a1-33c7-43de-935b-deba3b94b2c4.gif) ](https://user-images.githubusercontent.com/12072395/273653677-df6da3a1-33c7-43de-935b-deba3b94b2c4.gif) [ ](https://user-images.githubusercontent.com/12072395/273653677-df6da3a1-33c7-43de-935b-deba3b94b2c4.gif)

Even I'm facing this

**Comment by ZakGriffith** [comment]
Fixed in #119
