### ISSUE TITLE
Need consistent height and limits for Lists

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#117]
We should have a consistent height when displaying lists of different description lengths.  Let's also put a max character limit on the List name, description, and impact inputs.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/c657f77c-6ca9-4b47-8428-1bdd11082550)

**Comment by KcPele** [comment]
ok, will update it

**Comment by KcPele** [comment]
#122 fixed the issue

**Comment by ZakGriffith** [comment]
Fixed in #122
