### ISSUE TITLE
Unexpected behavior when using filters

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#120]
When using the filters on the project page it appears that the number in each filter is only displaying the count of the projects on that page alone, not all pages.  When clicking in, it will also only display the projects on that current page that match the criteria.  This is happening in both the grid and list views of projects.  These filters should always show the total number of projects that fit the criteria, and push them all into as few pages as possible when clicking, instead of leaving the projects on the page where they were initially displayed.

![FiltersPages](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/b5de6742-54ae-4f91-82d5-dc9d690b77d5)

**Comment by KcPele** [comment]
This happens because of the way the projects are being fetched. the pagination happens in the backend, so there will be no way to know all the categories. When a user clicks on next, it fetches it from the backend which is efficient.

**Comment by ZakGriffith** [comment]
Fixed in #154
