### ISSUE TITLE
Project card images and icon updates

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#123]
The image on the BuidlGuidl card is too big and makes the card huge, let's just use the top part of the image so it ends up being the size of the other blank cards.  So it would just show this part:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/d242e5ce-8815-4ce0-a78b-6603bd234e59)

All icons should be forced to have the same width and height.  That way when someone is entering a project, they can upload any square image and it will scale it down to fit and be the same size as the rest. So this icon here should have the same height and width, along with all other icons:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/f2e5855c-cd46-4c6a-9494-bd6225c3a69d)

For now, since time is a factor, let's reuse the buidlguidl image and icon for every project.

Once more note is that the list view of the projects should get the icons as well.  Currently they are all set to the walletConnect logo.
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/be6ce5f9-5749-4c00-9a8a-b7e92474966d)

**Comment by KcPele** [comment]
working on this

**Comment by ZakGriffith** [comment]
I think we have multiple folks working on this one.  All good, just giving a heads up.

**Comment by KcPele** [comment]
This is now completed #131
