### ISSUE TITLE
Projects in grid view need a border

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#124]
The project cards in the grid view need a border like they have in the list view

Grid view:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/b9eb50f3-a996-46b1-b10c-21ef0ba694d3)

List view:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/f385e22f-3aa9-4568-b227-d1466972710e)

**Comment by KcPele** [comment]
woking on this

**Comment by ZakGriffith** [comment]
Fixed in #125
