### ISSUE TITLE
Suggested Projects no longer populates

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#127]
This was populating as of a few PRs ago. Not sure what changed.
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/25259f00-fda6-427d-aa59-ce26ab8fc07d)

**Comment by electrone901** [comment]
It is still working for me using this link: 
https://op-retropgf3-discovery-voting.vercel.app/projects

**Comment by KcPele** [comment]
This is working fine

**Comment by KcPele** [comment]
This is fixed
