### ISSUE TITLE
Remove grid, list, and shuffle buttons from View Ballot page

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#128]
The grid view, list view, vertical divider line, and shuffle buttons can be removed from the View Ballot page as they are not necessary.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/f99eb525-a519-4baa-8f9f-5889b5658d8c)

**Comment by electrone901** [comment]
I can help with these

**Comment by KcPele** [comment]
can i help with this

**Comment by electrone901** [comment]
working on it

**Comment by ZakGriffith** [comment]
Closed in #132
