### ISSUE TITLE
Project views need the project image and icon.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#129]
This one is related a bit to Issue #123

Currently all project views use the same Orbiter Finance image and icon.  Since we now have a good project image and icon to play with in the Ospace Project(The BuidlGuidl website image and icon), we should get that same image and icon from the project grid view implemented in the view when you click into a project.

![ProjectView](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/a8aff260-08e8-4221-bc74-c1fb125d8cbd)

**Comment by electrone901** [comment]
if need it, I can help too

**Comment by KcPele** [comment]
Can i help with this

**Comment by electrone901** [comment]
working on this  now

**Comment by electrone901** [comment]
Should we close this issue @escottalexander ?

**Comment by escottalexander** [comment]
Resolved in https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/pull/136
