### ISSUE TITLE
List view needs truncated for long descriptions.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#133]
The description of a list needs truncated while in the horizontal view in the same way the projects list does it.

List horizontal:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/4fd32918-31ea-445b-8ceb-ddcd7ab8cc1f)

Project horizontal:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/a8b0e740-30fb-4159-8eb2-c4b4285080f8)

**Comment by electrone901** [comment]
I can also do this one

**Comment by ZakGriffith** [comment]
Closed in #173
