### ISSUE TITLE
Projects pagination limit

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#139]
**use-real-data branch**

In the project page, we now have a much larger number of projects which is causing the pagination system to extend too far.  This is occurring in both the grid and horizontal views.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/14c6e751-0c60-4149-b9cd-0453906a6a52)

Let's limit the visible number pages at any time to 5 or so.  Also up for discussion are buttons to jump to the very beginning or end.

**Comment by KcPele** [comment]
Fixed
![Screenshot from 2023-10-27 06-19-11](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/64108987/b364c1b7-489b-4f26-8ed3-0037b28987f9)
