### ISSUE TITLE
Projects not loading in single project page

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#142]
**use-real-data branch**

When attempting to load into a single project from the projects tab, the project info is not loading/displaying and stays as a loading icon.  Getting this error in the console:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_id')
    at loadListProjectsData (Card.tsx:29:15)
    at async populateList (Card.tsx:42:20)

**Comment by escottalexander** [comment]
I got this.

**Comment by ZakGriffith** [comment]
Closed in #147
