### ISSUE TITLE
Voting modals look incorrect

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#143]
Since we got the images and icons working, the pop-up voting modal doesn't look the same way and appears to be inside of the project card. 

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/9e2f5fb1-a479-49eb-b0f5-e396559884a3)

Those will need fixed to look as they did before the update similar to this and be "above" the project card area.
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/a94c0672-3086-4f5c-a69d-5fe2706861bb)

**Comment by KcPele** [comment]
working on it
