### ISSUE TITLE
Format filters

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#144]
**use-real-data branch**

On the project page filters, let's remove the underscores and also set the capitalization correctly. e.g. Collective Governance.
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/c29fd492-180d-4fe9-b8fe-e2b7fe69a740)

The capitalization also needs fixed in the list filters as well
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/1c24b446-ecde-4fae-8d5c-fc8da5331b7c)

**Comment by KcPele** [comment]
Done, pr will be made

**Comment by KcPele** [comment]
Done

**Comment by escottalexander** [comment]
Your changes look good on the category filters but lets leave this open until this also applies to the project categories inside each project card and on project page.
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/c25b9675-bbf9-4ead-9a3d-b1fcb5e5f880)
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/ee59db9a-dba9-41f5-ae01-6cff8bfe78ae)

**Comment by KcPele** [comment]
Fixed
