### ISSUE TITLE
Project horizontal spacing

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#145]
In the horizontal project view, let's make the logo larger and centered vertically, and also get the text and categories spaced closer together horizontally to make the height of each submissions smaller.  This will allow for faster scrolling though the large number of projects.

Currently:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/bce9583c-173a-4955-b3f8-2fd37aa641a7)

**Comment by KcPele** [comment]
Working on it

**Comment by KcPele** [comment]
![Screenshot from 2023-10-17 19-16-22](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/64108987/ae4d78f2-6896-4755-8f4a-dc44559b5884)
Is this ok

**Comment by escottalexander** [comment]
I just merged in this change but I think an improvement would be for the icon to be vertically aligned in the center. Right now it is slightly above center.

**Comment by ZakGriffith** [comment]
Agree, aligned with the top and bottom borders of the card would be a nice touch.

**Comment by KcPele** [comment]
Perfect

**Comment by KcPele** [comment]
Done
