### ISSUE TITLE
Only one project can be added to Ballot

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#148]
Currently when you're adding projects to the ballot, only the first one you click actually get put on the ballot.  The next ones you click, it looks like it works, but then they are not on the Ballot.

![AddToBallot](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/eb7079a6-c986-4464-8eb8-84ff784cb772)

**Comment by Chirag018** [comment]
Will have a look at it

**Comment by escottalexander** [comment]
I think this is fixed. Probably just bad type issues. Test again and close.

**Comment by Chirag018** [comment]
OK

**Comment by ZakGriffith** [comment]
Yup, this is working now.
