### ISSUE TITLE
Shuffling and Filtering is by page

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#154]
When you click shuffle or use one of the filters it just filters the projects on the existing page or shuffles the projects on the existing page. We need it to filter by all projects and shuffle all projects, returning a whichever random ones are on the new shuffled patterns first page.

**Comment by escottalexander** [comment]
#120 is also related to this.

**Comment by blahkheart** [comment]
PR created for this issue

**Comment by ZakGriffith** [comment]
Fixed in #175
