### ISSUE TITLE
List sharing modal should match design

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#157]
Currently looks like this:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/cdfa7854-c179-46ca-831c-6928add10d60)

Needs to match the general style and feel of the project. There is no design in the design doc unless I missed it.

**Comment by KcPele** [comment]
Working on it

**Comment by KcPele** [comment]
Since there is no design, I think we can go with this

**Comment by escottalexander** [comment]
I think we can do better than leaving as is. Here is an example of another modal: 
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/f5284875-c498-48d5-988c-af79a9a77620)
Lets adjust the layout, fonts, button styles/colors to match this one.

**Comment by KcPele** [comment]
Working on it

**Comment by ZakGriffith** [comment]
Closed in #180
