### ISSUE TITLE
Error when adding to ballot from single project page

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#160]
When clicking Add To Ballot when clicked in to a single project the following error occurs.  Doesn't happen when adding from projects grid or horizontal cards.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/45755e2d-11bd-4085-b17f-3ea527b210c1)

**Comment by KcPele** [comment]
Working on this

**Comment by KcPele** [comment]
This has been fixed

**Comment by ZakGriffith** [comment]
Fixed
