### ISSUE TITLE
Suggested projects blank when looking at a list.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#165]
There is a suggested projects section when you've clicked into a list.  It is at the bottom of the page and blank.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/e4ac36f1-6b29-4568-8f78-d1effb5d03d2)

Since we're looking at a list already, we can safely remove the suggested section from that page.

**Comment by KcPele** [comment]
Removal has successful

**Comment by ZakGriffith** [comment]
I am still seeing the suggested projects when viewing a list.  Is this fix coming in a new PR?

**Comment by electrone901** [comment]
I can help if need it

**Comment by ZakGriffith** [comment]
Fixed in #174
