### ISSUE TITLE
Some project's icons shrink when resizing in horizontal view

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#167]
When in the project tab, horizontal view.  When checking different windows sizes, some of the project icons width shrinks.  Snapshot and EtherScore are examples of this. 

![ProjectIconShrink](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/cc2b1355-0d3f-492f-bb74-8e6b68af7896)

**Comment by KcPele** [comment]
Fixed

**Comment by ZakGriffith** [comment]
Closed in #169
