### ISSUE TITLE
In lists grid view, the button moves to the left side when no category was selected.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#176]
When a list is created with no category/description, the Add To Ballot button slides to the left of the card while in grid view.  It should stay in the right side location.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/94d2b7ee-1ff0-41aa-b6d5-dc0eaa64c6ca)

**Comment by electrone901** [comment]
I can help with this

**Comment by electrone901** [comment]
can we close this issue?

**Comment by ZakGriffith** [comment]
Sure enough, good call!
