### ISSUE TITLE
Site icon

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#45]
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/a19d3ba3-e9a0-48dd-973b-3fa847ee0b68)
 Currently there is no icon for the site. Lets ask Jonas what should be used here and implement. Maybe a tiny OP symbol?

**Comment by electrone901** [comment]
I can start with this =)

**Comment by escottalexander** [comment]
Any progress on this? I can pick it up if it is at a standstill.

**Comment by electrone901** [comment]
Hi @escottalexander, sorry for the delay but got busy with ETHNewyork. I can work on it.

**Comment by KcPele** [comment]
have u started working on this

**Comment by electrone901** [comment]
yes

**Comment by ZakGriffith** [comment]
Fixed in #89
