### ISSUE TITLE
Countdown timer

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#46]
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/761fc6c1-4c63-498c-a530-73ea41a0ca8a)
Currently this is just fixed text. Add countdown functionality. This will be a fixed date that we can set either in the database or hardcoded but perhaps as a first pass we could arbitrarily set a date a month in the future so we can demonstrate the countdown working.

**Comment by luloxi** [comment]
Where is this information gonna be read from? 

I could do something similar to what I used [here](https://github.com/luloxi/evolution-DAO/blob/khazum/packages/react-app/src/views/ProposalCard.jsx) for a countdown and a dynamic text that changed after the deadline was reached (Time left/Ended on), just got to change the format

**Comment by escottalexander** [comment]
It will probably read from a database value that is set. Feel free to set that up or just hardcode an end date to demonstrate the functionality. We would need feedback from OP to know what they want it to do when it has ended but that sounds great!

**Comment by luloxi** [comment]
I assumed it'd be a timestamp on a smart contract, but it can be adapted to any other format :grinning:
