### ISSUE TITLE
Ballot Review

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#47]
Ballot page needs to look like designs. 
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/2c095808-2f3a-43f2-977b-06f4373053ab)
Currently it looks like this:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/90bc7d1c-0e51-4639-8193-1f632ee86ec2)
A UI component does exist that fits the design but it will need to be integrated with any functionality on the current ballot page.

**Comment by Chirag018** [comment]
working on this!

**Comment by escottalexander** [comment]
To be clear, The change that needs to be made is that when you click on "View Ballot" it needs to send you to the "My Ballot" view. Currently it sends you to this other "review ballot" but it does not match the designs. Also, there is already an element that looks like the "My Ballot" page that exists. It may lack some of the functionality that the "review ballot" page has though.

**Comment by escottalexander** [comment]
@Chirag018 You should get latest from the main branch as I just merged in a change that removes the dropdown when the view ballot button is clicked.

**Comment by Chirag018** [comment]
Yeah, working on the ballot page design, there is no issue in having it here/can also pop this out for a new issue and close this one for that as well.
