### ISSUE TITLE
View Ballot Button Function

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#48]
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/d7cda094-1b93-47df-8194-fae51a602a12)
Clicking the view ballot button should drop users off on the review ballot view.

**Comment by gotnoshoeson** [comment]
Dibs, should be able to pick this one up today.

**Comment by gotnoshoeson** [comment]
So you don't want this preview modal to show? You just want the "View ballot" button to redirect directly to "/ballot-review"?

**Comment by escottalexander** [comment]
Correct! You should be able to find the figma design in TG. If not, then dm me.
