### ISSUE TITLE
Background color adjustment

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#49]
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/ec7de311-e633-4fc3-b45b-ceabd6353728)

Currently the color for the background throughout the site is not #ffffff as it should be. Is this something we can adjust in the tailwind config?

**Comment by Chirag018** [comment]
working on this as well!!
