### ISSUE TITLE
Pagination Functionality

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#50]
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/92323345-3a3f-44b6-88b1-eb60d15c0b60)

Currently the pagination looks great but doesn't work. We want to add logic that makes pagination only appear when needed and then when clicked takes the user to more paginated results.

**Comment by blahkheart** [comment]
Working on this
