### ISSUE TITLE
Edit distribution on project page

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#51]
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/05f3b08a-2420-477f-ab2c-0f91a9652529)
Currently if you click the edit distribution button it opens a modal that does not inherit the project details and is also not editable.
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/e927877d-5dea-4dc3-b833-c3ea77089026)
Let's fix that.

**Comment by KcPele** [comment]
Also working on this

**Comment by ZakGriffith** [comment]
Fixed in #59
