### ISSUE TITLE
Add To Ballot Button on Project Page

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#52]
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/979f97ad-ffcf-4267-a011-f138a2c30b0f)
Currently when you click this button it adds the project with 0 OP allocated. The correct workflow will open this modal (which exists already but isn't functional)
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/a4fdbba4-ff38-42e7-9144-f6bd8b05e582)

**Comment by KcPele** [comment]
an update has been made to the modal, try and check it out

**Comment by KcPele** [comment]
@Chirag018 u can check this #59 it has similar functionality.

**Comment by Chirag018** [comment]
@escottalexander it was already solved in #80, so now is there a need for this PR?

**Comment by escottalexander** [comment]
Yes. This was already resolved. Thanks!
