### ISSUE TITLE
Edit Distribution modal number input

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#53]
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/22101475/fda58b1d-e267-47fb-86b5-8b3d7a8926b8)
The number input is a little janky in that it doesn't allow you to backspace without appending a mandatory 0 which doesn't go away when you add a whole number. One solution is to add a onChange function that parses the input to a more usual look and feel before updating the state.

**Comment by KcPele** [comment]
Working on this

**Comment by KcPele** [comment]
Done

**Comment by ZakGriffith** [comment]
Fixed with #57
