### ISSUE TITLE
HandleAddBallot is not defined

### ISSUE THREAD

**Issue by Chirag018** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#55]
On edit distribution after adding to the ballot, while clicking on save => the error pops up

<img width="938" alt="Screenshot 2023-09-12 at 1 10 50 PM" src="https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/56735482/4ba8047b-9028-4199-80ea-0efa87c0f57c">

Reference: #52

**Comment by KcPele** [comment]
fixed

**Comment by ZakGriffith** [comment]
Fixed in #59
