### ISSUE TITLE
Button test hidden in dark mode.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#60]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

The text after expanding the three-dot button in the project view doesn't not appear in dark mode.  

![ButtonText](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/42adae62-8fb8-4cda-b205-6c7face7e3b9)

**Comment by Chirag018** [comment]
working on this

**Comment by Chirag018** [comment]
A similar issue occurs in the View ballot as well(in dark mode).
<img width="438" alt="Screenshot 2023-09-17 at 9 19 48 PM" src="https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/56735482/683c292e-29f4-40f6-8b45-32c726d5c50e">
<img width="449" alt="Screenshot 2023-09-17 at 9 20 10 PM" src="https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/56735482/3736c358-f3fc-4d26-ab40-ce078f0283fb">
