### ISSUE TITLE
Three dot button stays after editing distribution.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#61]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

In the project view, the three dot button pop-up stays there even after clicking a button and changing the distribution.  This pop-up should hide as soon a button is pressed in it's menu.

![ThreeDotDisappear](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/52ed262f-1e9e-42d2-8abb-5f3f896fd842)

**Comment by KcPele** [comment]
Working on it

**Comment by Chirag018** [comment]
Hey, @KcPele I have been working on this as well simultaneously, but forgot to update it here. As a part of #62 

If you haven't started can you drop it?

**Comment by KcPele** [comment]
Ok
