### ISSUE TITLE
When using the Edit Distribution modal, the distributions doesn't actually update and any number is allowed.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#62]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

When using the Edit Distribution modal, any number is allowed to be set as the new distribution, even if it is higher than their remaining distribution.  Then after saving the distribution, it doesn't actually save it as seen in the video.

(I also ran into the Edit Distribution modal randomly disappearing when I tried to highlight and delete the 0, but that will be another Issue after testing)

![EditDistribution](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/3ac217aa-4665-45f2-bfea-7787b938c85f)

**Comment by KcPele** [comment]
Working on it

**Comment by Chirag018** [comment]
Hey, @KcPele I have been working on this as well simultaneously, but forgot to update it here.

If you haven't started can you drop it?
