### ISSUE TITLE
View Ballot & Address buttons in Firefox Browser

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#66]
When using Firefox, the View Ballot and Address button padding are not displaying the same way as other browsers.  Here is whatI see using Firefox:

![Buttons](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/faad3a6d-cecf-4f45-ba4f-7d4944a5631a)

Here is what it looks like (correct) in Chrome:

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/920346c4-1d44-47d0-901b-53473fc55a61)

Also the capitalization should be updated to be consistent between light and dark mode.  I don't have a preference between "View Ballot" or "VIEW BALLOT", but they should be the same.

**Comment by escottalexander** [comment]
I got this.
