### ISSUE TITLE
Dark Mode Issues

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#67]
The background isn't updating when switching to dark made, causing quite a few items to become invisible.

Also the current tab's text color needs to change when in dark mode as it is also very hard to see.

![DarkMode](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/55a8ed51-1198-40fe-a53c-1e7c28b1dcac)

**Comment by gotnoshoeson** [comment]
Oh shoot. I'm working on this too. @luloxi

**Comment by ZakGriffith** [comment]
This looks good!  Found a couple more places that I was unaware of before.  The current selected page in the List view, and the All button next to the Liked button as seen in this screenshot.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/7466b7e3-7ced-4c25-b093-4d7701ade165)

**Comment by ZakGriffith** [comment]
Whoops, found another after more testing.  When you click into a section to filter it:  

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/7c13b209-0c11-4933-936d-37d7ec17ab59)
