### ISSUE TITLE
Light mode project cards need a border.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#68]
The project cards in light mode don't look right with no border.  They should be updated to be more similar to the projects tab in the Figma file:  

https://www.figma.com/file/LLwuijWZJC6bhmgE284VFB/%5BVit%5D---RetroPGF---Voting-(Copy)?type=design&node-id=630-64825&mode=design&t=r8H6KXEoE0ldH7nX-0

Here is what I am currently seeing:  

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/c754586d-90d1-4bb1-9ad8-f361bf60d61b)

But they should be more like:  

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/eb110905-35a7-45f2-9083-f2d1544c43f1)

**Comment by escottalexander** [comment]
I got this.
