### ISSUE TITLE
Pagination shouldn't shift right when on last page.

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#77]
As seen here when getting to the last page the pagination system shifts to the right when the Next button disappears.  That causes some confusion.  The other buttons should stay located in the same spot even when on the last page and the Next button is gone.

![Pagination](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/aeb6622d-a976-413e-ad80-494bc2286bf4)

**Comment by ZakGriffith** [comment]
Keep in mind there is also an ongoing Issue of adding the underlying functionality to these buttons (Issue #50), so if you are tackling this issue you may want to reach out to @blahkheart to make sure we're not messing anything up with that.

**Comment by gotnoshoeson** [comment]
Looks like blahkheart's PR addresses this issue
