### ISSUE TITLE
Allocation Issues

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#82]
There are a handful of bugs that exist when using the project page to allocate votes.  

On the pop-up modal when clicking Edit Distribution, then typing a non-number, the field will display NaN.  You can delete out the NaN and continue, but if you leave the NaN and click Save, the main allocation bar fills up and displays a NaN.  NaN is also displayed on the OP Allocated area of the project page.  If you edit distribution again and choose a regular number, then allocated votes returns to normal.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/4778fee8-d79e-461b-869c-76813f5be4f8)
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/59e73793-f934-4334-b7f6-b5dd9b1759ba)

When adding a project to the ballot, then choosing any number (other than 1), the votes will appear in the red allocation bar, but the red Op Allocated section will display a 1.  Then clicking back into the Edit Distribution button also shows a 1.  

![AllocationBug](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/2657821c-47ae-4ab5-a1f0-6eebdf6e2d12)

Similar to the above, the modal for the Add To Ballot and Edit Distribution needs to be locked to only allow the max allocation.  In our case that is 100.  There is very sporadic behavior if numbers higher than 100 are entered.  It should allow a max of (current allocated votes + number entered in modal).

**Comment by blahkheart** [comment]
I'll work on this

**Comment by blahkheart** [comment]
Issue closed

**Comment by ZakGriffith** [comment]
Fixed in #90
