### ISSUE TITLE
List View Issues

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#86]
In the Lists tab, the width of the cards in the grid view is now too narrow when on a wider screen.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/9d065da8-165a-4ed2-80ab-196e24524d55)

Remove the vertical line to the right of the Liked button as it is a divider but there is nothing to it's right side.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/b9fe6eb3-789c-4639-b432-c67f9a9481e2)

If the user has no "liked" lists yet, lets display some text saying that.  Something like "You have not liked any lists yet" as the current view looks off.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/eccfd91f-89a6-41e1-910e-d3265f66b3a2)

The All tab might also need "There are no lists yet"  if there are no Lists yet created, but I can't test that.

**Comment by electrone901** [comment]
I can help with this

**Comment by ZakGriffith** [comment]
Going back to this, I would like to see it with more lists.  Maybe this is the appropriate width and there is supposed to be three per row?  Even so, the two in the screenshot should be next to each other if that's the case.

**Comment by electrone901** [comment]
Sounds good let me take a look
