### ISSUE TITLE
Mobile View Dark Mode Button

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#87]
Currently when viewing on mobile, the switch to dark mode button (In the three line nav menu button) is just a blank bubble.  That should be the real dark mode logo like the other.  Let's also decrease the space between the light/dark buttons and the address.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/de035016-d70a-4b9f-8b03-85ea92c1f4ef)
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/bdbc8c3c-1dc0-44b8-84dc-5ac7f102c36c)

**Comment by KcPele** [comment]
i will handle this

**Comment by KcPele** [comment]
Here is the fix #98

**Comment by escottalexander** [comment]
Merged!
