### ISSUE TITLE
Liked Projects Tab

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#88]
Currently "Liked" projects are not displaying in the Liked tab.  Is it possible to implement that now, or do we have to wait until we get OP's information.  If we can do it now, let's do.

![LikedTab](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/b898b7a8-c64a-471d-8e19-5f0dab2f6c50)

The shuffle button in the Liked tab doesn't seem to have any effect (Although it's tough to test with just two).  Let's implement a list shuffling like in the projects page.

![Shuffle](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/4410ee3c-de3a-4744-a93a-ca90c8bf8176)

**Comment by blahkheart** [comment]
i'll work on this

**Comment by ZakGriffith** [comment]
Fixed in #119
