### ISSUE TITLE
Request - Op Allocated Link

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#91]
Let's have this thing:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/40174c63-2a26-4903-9fdb-c9f5b8707a65)
Link to this Edit Distribution modal:
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/ac4eac32-005b-41d3-91b7-1ec04d8202e4)

**Comment by Chirag018** [comment]
will work on this!
