### ISSUE TITLE
Request - Larger link on project card

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#92]
It would be handy if this entire card was the link to the project page instead of just the project title.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/22871f68-9bc6-47b5-bf75-ffc9c8ae34df)

The only caveat is that this little section:  
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/f7b6707d-739f-4140-991a-1538735f0725)
should not be part of the link but instead just highlight that filter like here: 
![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/13d1d85b-dbff-4315-b186-de99eb1e1d46)

**Comment by Chirag018** [comment]
Will work on this

**Comment by ZakGriffith** [comment]
Closing this one as it was fixed when a similar issue was found in the 'wide' view of projects in Issue #105 
All fixed in PR #110

**Comment by Chirag018** [comment]
It was already done with PR. 94
