### ISSUE TITLE
Add Add To Ballot / X OP Allocated button to project card

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#93]
For those who don't need to click into a project to learn about it, it would be helpful to have the Add To Ballot / X OP Allocated button right on the project card and list view of the the project.  

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/e208e7e1-dfd6-4b2e-a44d-6c3f8c84030f)

**Comment by blahkheart** [comment]
I'm working on this

**Comment by ZakGriffith** [comment]
Fixed in #119
