### ISSUE TITLE
Vote allocation modal auto closes when highlighting text

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#96]
The distributions modal will close when highlighting the number in the field, and letting off the mouse when the cursor is off the modal.  This is happening in Chrome and Brave, but not in Firefox.  If you let off the click with the mouse cursor still on the modal or use backspace to delete, it works as intended.  This happens when both using the Add To Ballot or Edit Distribution buttons.

The expected behavior it that the modal should stay open, even when you quickly highlight the text and finish with the cursor outside the modal.

Another good addition for this would be to set the focus in the input when this modal opens, so the user doesn't have to click in to edit the number.

![ModalClose](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/701965f2-d935-4b11-ae7b-f0897fd317f4)

**Comment by gotnoshoeson** [comment]
Just setting the focus should clear up the UX.

**Comment by blahkheart** [comment]
That's right @gotnoshoeson I'm already working on some related issues hope you don't mind if I fix this up along with them.

**Comment by ZakGriffith** [comment]
Fixed in #119
